drop:
    resource: "@DropBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@DropBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin