drop:
    resource: "@DropBundle/Resources/config/routing.yml"
    prefix:   /

security_login:
    path: /login
    defaults: { _controller: DropBundle:Security:login }

security_logout:
    path: /logout
    defaults: { _controller: DropBundle:Security:logout }