# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        DropBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity:
                class: DropBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login: ~
            guard:
                authenticators:
                    - DropBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout

            switch_user: ~

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
