Droparea\DropBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Droparea\DropBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productCode:
            type: integer
        category:
            type: string
            length: 255
        image:
            type: string
            length: '1000'
        name:
            type: string
            length: 255
        weight:
            type: integer
        price:
            type: string
            length: 255
        recomendedPrice:
            type: string
            length: 255
        сщcostReturn:
            type: string
            length: 255
        valuta:
            type: string
            length: 255
    lifecycleCallbacks: {  }
