<?php

namespace Droparea\DropBundle\Controller;

use Droparea\DropBundle\Entity\Product;
use Droparea\DropBundle\Form\Type\ProductType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class PatronController extends Controller
{
    public function indexAction(Request $request)
    {
        if ($city = $request->request->get('update-data-address')) {
            $postAddress = $this->get('fetch.new.post.address');
        }

        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        $em = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $product->getImage();

            $imageName = $this->generateUniqueFileName().'.'.$image->guessExtension();

            $image->move(
                $this->getParameter('images_directory'),
                $imageName
            );

            $product->setImage($imageName);

            $data = $form->getData();
            $em->persist($data);
            $em->flush();
            return $this->redirectToRoute('patron', [
                'success' => 1,
            ]);
        }

        $success = $request->get('success');

        return $this->render('@Drop/Patron/main-patron.html.twig', [
            'form' => $form->createView(),
            'success' => $success,
        ]);
    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
