app:
    resource: "@DropBundle/Controller/"
    type: annotation

patron:
    path: /patron
    defaults: { _controller: DropBundle:Patron:index }

user_register:
    path: /registration
    defaults: { _controller: DropBundle:User:registerUser }

user_page:
    path: /user-page
    defaults: { _controller: DropBundle:User:showUserPage }
