drop_homepage:
    path:     /
    defaults: { _controller: DropBundle:Default:index }
patron:
    path: /patron
    defaults: { _controller: DropBundle:Patron:index }

products:
    path: /products
    defaults: { _controller: DropBundle:Default:products }

products-category:
    path: /products/{category}
    defaults: { _controller: DropBundle:Default:products, category: 0 }

product:
    path: /product/{id}
    defaults: { _controller: DropBundle:Default:oneProduct }

orders:
    path: /orders
    defaults: { _controller: DropBundle:Default:orders }

new-orders:
    path: /new-orders
    defaults: { _controller: DropBundle:Default:newOrders }

payments:
    path: /payments
    defaults: { _controller: DropBundle:Default:payments }

statistic:
    path: /statistic
    defaults: { _controller: DropBundle:Default:statistic }

referrals:
    path: /referrals
    defaults: { _controller: DropBundle:Default:referrals }

news:
    path: /news
    defaults: { _controller: DropBundle:Default:news }

ajax-new-post:
    path: /ajax-new-post
    defaults: { _controller: DropBundle:Default:ajaxNewPost }

user_register:
    path: /registration
    defaults: { _controller: DropBundle:User:registerUser }

user_page:
    path: /user-page
    defaults: { _controller: DropBundle:User:showUserPage }