<?php

namespace DropBundle\Repository;

/**
 * OrdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdRepository extends \Doctrine\ORM\EntityRepository
{
}
