<?php

namespace DropBundle\Repository;

/**
 * PostAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostAddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastUpdatedPostAddress()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}

