<?php

namespace DropBundle\Repository;

/**
 * PostAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
