<?php

namespace DropBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMultipleId(array $id)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->select('p')
            ->where($qb->expr()->in('p.id', $id))
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllProductsQuery()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery();
    }

    /**
     * @param $category
     * @return \Doctrine\ORM\Query
     */
    public function findAllProductsByCategoryQuery($category)
    {
        return $this->createQueryBuilder('p')
            ->where('p.category = :category')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('category', $category)
            ->getQuery();
    }
}
