<?php

namespace Droparea\DropBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMultipleId(array $id)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->select('p')
            ->where($qb->expr()->in('p.id', $id))
            ->getQuery();

        return $query->getResult();
    }
}
